name: Code Execution

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up GCC
        if: ${{ contains(steps.check.outputs.files, '.cpp') }}
        uses: dante-ev/ubuntu-gcc@v1

      - name: Compile C++ code
        if: ${{ contains(steps.check.outputs.files, '.cpp') }}
        run: |
          g++ -o output main.cpp
          ./output > result.txt

      - name: Set up Java
        if: ${{ contains(steps.check.outputs.files, '.java') }}
        uses: actions/setup-java@v3
        with:
          java-version: "11"

      - name: Compile Java code
        if: ${{ contains(steps.check.outputs.files, '.java') }}
        run: |
          javac Main.java
          java Main > result.txt

      - name: Upload results
        if: ${{ contains(steps.check.outputs.files, '.cpp') || contains(steps.check.outputs.files, '.java') }}
        uses: actions/upload-artifact@v3
        with:
          name: results
          path: result.txt

      - name: Check for code files
        id: check
        run: |
          files=$(find . -type f \( -name '*.cpp' -o -name '*.java' \))
          echo "files=$files" >> $GITHUB_ENV
